---
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - <path to Config Folder>:/config
      - <path to Calibre Database Folder>:/books
    ports:
      - 8083:8083
    restart: unless-stopped
    networks:
      default:
      external:
        name: calibre-web_default
