services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PWD}
      MYSQL_DATABASE: nextcloud_db
      MYSQL_USER: ${SQL_UID}
      MYSQL_PASSWORD: ${SQL_PWD}
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: nextcloud:27-apache
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud_db
      MYSQL_USER: ${SQL_UID}
      MYSQL_PASSWORD: ${SQL_PWD}
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: ${NC_ADMIN_PWD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NC_TRUSTED_DOMAINS}
    volumes:
      - nextcloud_data:/var/www/html
volumes:
  db_data:
  nextcloud_data:
